services:
  postgres:
    image: postgres:16-alpine
    container_name: hr-system-postgres
    environment:
      POSTGRES_DB: hr_system_db
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
    ports:
      - "5425:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_user -d hr_system_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
